POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "nam",
  "email": "nam@gmail.com",
  "password": "12345678"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "ducanh@gmail.com",
  "password": "12345678"
}

###
POST http://localhost:5000/api/post/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTNkY2E4OGJkMjk5MjRkMTcyZGQ1MWQiLCJpYXQiOjE2MzIxNTIwNzN9.H6mK5nWU-zXHwtgXP84WoDSZjNVmEENmhX5BTE46N-k

{
  "desc": "This is DucAnh's second post",
  "image": "image.png"
}

###
PUT http://localhost:5000/api/post/6148aa1ed91bdba9cb47f698
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTNkY2E4OGJkMjk5MjRkMTcyZGQ1MWQiLCJpYXQiOjE2MzIxNTIwNzN9.H6mK5nWU-zXHwtgXP84WoDSZjNVmEENmhX5BTE46N-k

{
  "desc": "Updated post second time",
  "image": ""
}

###
GET http://localhost:5000/api/post/6148aa1ed91bdba9cb47f698
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTNkY2E4OGJkMjk5MjRkMTcyZGQ1MWQiLCJpYXQiOjE2MzIxNTIwNzN9.H6mK5nWU-zXHwtgXP84WoDSZjNVmEENmhX5BTE46N-k

###
DELETE http://localhost:5000/api/post/6148aa1ed91bdba9cb47f698
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTNkY2E4OGJkMjk5MjRkMTcyZGQ1MWQiLCJpYXQiOjE2MzIxNTIwNzN9.H6mK5nWU-zXHwtgXP84WoDSZjNVmEENmhX5BTE46N-k
